name: .NET Core

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
       working-directory: ./api
       dotnet-version: 6.x.x
    - name: Run dotnet watch
      run: dotnet watch --project/api/API.csproj run
