name: Cypress tests

on: [push]

jobs:
  dotnet-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
       working-directory: ./api
       dotnet-version: 6.x.x
    - name: Run dotnet watch
      run: dotnet watch run --project API/API.csproj &      
    - name: Cypress run
      uses: cypress-io/github-action@v2.9.1
      with:
            working-directory: ./client
            run: npm i
            build: npm run build
            start: npm start
            cypress-version: '12.2.0'
            config-file: cypress.config.ts
            record: true
      env:
        CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
 
